### ISSUE TITLE
Extending to StackExchange

### ISSUE THREAD

**Issue by uomoinverde** [StylishThemes/StackOverflow-Dark#10]
How can I safely edit the source to make this dark theme available to the whole of StackExchange network (if it is possible, of course)?

**Comment by thoroc** [comment]
:+1:

**Comment by muntoo** [comment]
I think @Mottie is a time lord who has gone lost in time.

**Comment by Mottie** [comment]
@muntoo I can't tell you much, but I can say that by 2025, there will one style to rule them all.

**Comment by ddavison** [comment]
K&R

**Comment by Mottie** [comment]
This style will now automatically apply to almost every StackExchange site, except:

  * Area 51 (area51.stackexchange.com)
  * Gaming (gaming.stackexchange.com)
  * Rope Playing Games (rpg.stackexchange.com)

Mostly due to those sites having a lot of extra styling.

I didn't thoroughly test every single StackExchange site, so I'm sure there are some broken styles out there. If you find any issues, please report it here, or even better fix it, and submit a pull request :grin:
