### ISSUE TITLE
Profile Settings -> Slack integrations needs to be added

### ISSUE THREAD

**Issue by cornfeedhobo** [StylishThemes/StackOverflow-Dark#109]
If you navigate to your profile's / team's settings, there is a newer option for Slack integration, and it looks like CSS for it has not been added.

Example url: `https://stackoverflow.com/users/integrations/slack/<user id>`

**Comment by Mottie** [comment]
Hi @cornfeedhobo!

I am not seeing any "Integrations" section on Stack Overflow... is it new? Maybe they are A/B Testing the setting?

I do see that some of the header text isn't being styled properly, so I'll fix that.

**Comment by cornfeedhobo** [comment]
@Mottie Maybe it's only for companies that are using their new [channels](https://stackoverflow.blog/2017/07/11/introducing-channels-private-qa-team/) offering. I can try to make a PR this weekend, but wanted to start with an issue to track it.

**Comment by the-j0k3r** [comment]
I cant get anywhere with this link `https://stackoverflow.com/users/integrations/slack/<user id>`

I added my slack ID as `<user id>` to URL
result

![capture](https://user-images.githubusercontent.com/31389848/52768845-dd3e7e80-302e-11e9-9475-245ed3894b20.PNG)

@cornfeedhobo if you submit a pr Ill be happy to have a look, but I cant even see the issue never mind repro in order to have a go at this.

**Comment by the-j0k3r** [comment]
ping

**Comment by cornfeedhobo** [comment]
I no longer use private SO. Sorry I didn't close this sooner.

**Comment by the-j0k3r** [comment]
@cornfeedhobo thanks for coming back to us.

We will be happy to have a look at this again any time in the future, if and when more actionable information is provided.

Thanks =)
