### ISSUE TITLE
uninstall instructions and suggestion

### ISSUE THREAD

**Issue by mlgiter** [StylishThemes/StackOverflow-Dark#111]
Could you add uninstall instructions to your install guide in order to revert back to standard?

BTW, i would appreciate for example having switchable to printable version styling, like stackprinter.com. 
If you master yours or know the solution, please let me know.
I believe it would be popular one.

**Comment by Mottie** [comment]
Hi @mlgiter!

Uninstalling the userstyle is based on which userstyle manager you're using.

If you're using Stylus, go to the manager and click the big "X":

![](https://user-images.githubusercontent.com/136959/40576354-5079f220-60ba-11e8-908b-26bb0bf3d12c.png)

Or, within the popup, click the trash can:

![](https://user-images.githubusercontent.com/136959/40576356-64af9fa6-60ba-11e8-9e87-993717bf884e.png)

It should be similar in Stylish, but I didn't bother with any screenshots because I don't use it anymore.

----

As for making a printable Stackoverflow page, it'd be better to be able to choose what you want to print. The selected answer is not always the best answer, and would you want to include comments? Not all comments are visible. And not all comments are worth printing.

I worked on a Chrome extension ages ago named [The Printliminator](https://chrome.google.com/webstore/detail/the-printliminator/nklechikgnfoonbfmcalddjcpmcmgapf) which would allow you to click elements to hide prior to printing. Maybe that'll help you? I haven't updated it in a while, nor it is always easy to use... maybe there are some other newer, better extensions that do something similar available.

**Comment by mlgiter** [comment]
Thanks for the answer, Mottie!
I will try out your extension. I would share my ideas about so printablity, if you mind.
Please tell me best way to contact you.
