### ISSUE TITLE
Stackexchange API docs

### ISSUE THREAD

**Issue by shawnmclean** [StylishThemes/StackOverflow-Dark#120]
* **Browser**: Chrome
* **Operating System**: MacOS 10
* **Screenshot**:
<img width="1075" alt="screen shot 2018-08-25 at 10 51 34 pm" src="https://user-images.githubusercontent.com/199751/44622868-80e97600-a8b9-11e8-8996-375b629a8628.png">

Url: https://api.stackexchange.com/

**Comment by shawnmclean** [comment]
Is there a way to blacklist api.stackexchange.com from stylish?

**Comment by Mottie** [comment]
Hi @shawnmclean!

We can exclude the site, or style it; it actually won't take too much longer to complete the styling.

Don't use Stylish, unless you don't mind them collecting data on every site you visit. That and we are no longer updating userstyles.org because the site and Stylish are owned by the same people.

Right now, neither Stylish nor Stylus have the ability to exclude/blacklist a site, but there is some [work-in-progress](https://github.com/openstyles/stylus/pull/360) adding it to Stylus.

**Comment by Mottie** [comment]
FYI, we'll add this usercss style to https://openusercss.org/ once they get the issue worked out with adding new usercss with custom variables.
