### ISSUE TITLE
Code block themes similar to GitHub-Dark

### ISSUE THREAD

**Issue by jawshooah** [StylishThemes/StackOverflow-Dark#13]
Would it be possible to customize the theme for code blocks as with GitHub-Dark? The bright blue coloring of keywords in the default style a bit too harsh for my taste. I'd like to be able to switch to Tomorrow Night Eighties or something similar if possible.

**Comment by Mottie** [comment]
Hi @jawshooah!

It looks like StackOverflow is using a [modified version of Google's Pretty Print](http://cdn.sstatic.net/Js/prettify-full.en.js?v=c847a58c54bf).  So, I'm not 100% sure all the class names will be the same.

It does look like there are a few [themes for prettyprint](http://jmblog.github.io/color-themes-for-google-code-prettify/), including the Tomorrow Night set. So you're in luck there, because I don't really have the time nor the inclination to convert themes over to pretty print.

So, that being said, I'll look into adding some themes to SO when I get some free time this weekend.

**Comment by Mottie** [comment]
Done in https://github.com/StylishThemes/StackOverflow-Dark/commit/0fd523d843c99b17b0b453727c422a4d57be712a

There is now a grunt build process... find [more details here](https://github.com/StylishThemes/StackOverflow-Dark/wiki/Build).

**Comment by jawshooah** [comment]
Awesome! Thanks for the quick turnaround :beers:
