### ISSUE TITLE
Since Userstyles.org isn't supported, how do I customize the background image?

### ISSUE THREAD

**Issue by spikespaz** [StylishThemes/StackOverflow-Dark#131]
And change the syntax highlighting. Do I need to fork and build the CSS manually?

**Comment by Mottie** [comment]
We stopped supporting Stylish & the ability to create a custom build because of [UserCSS](https://github.com/openstyles/stylus/wiki/UserCSS) and [Stylus](https://add0n.com/stylus.html) (or [xStyle](https://github.com/StylishThemes/StackOverflow-Dark#installation)). UserCSS allows you to control the customization from the browser instead of the website. All of the instructions can be found on the UserCSS wiki page linked to above.

**Comment by spikespaz** [comment]
Thanks.
