### ISSUE TITLE
Should still be on userstyles.org - nobody can find this or knows it exists now

### ISSUE THREAD

**Issue by notmutiny** [StylishThemes/StackOverflow-Dark#148]
I only found this because I had the code installed on a separate machine and was able to find the archived webpage which led me to here. This is so roundabout and unnecessary that if anyone is using the style they likely aren't going to anymore - not because it's bad but because nobody knows where it went, what it's called, or if it's even still in development.

Great theme, stupid migration choice.

**Comment by xt0rted** [comment]
I mentioned a way of handling this in https://github.com/StylishThemes/GitHub-Dark/issues/805#issuecomment-452801122.

I think it'd be a good idea to update all of the themes one last time with an alert and leave them published so people can more easily find them, but see right away that they should install it from the repo instead.

I think there will be less people annoyed by that then not getting updates or not finding the themes at all.

**Comment by the-j0k3r** [comment]
I think any updates should happen just to add that notice you've done @xt0rted, not actual style updates. 

From a past conversation regarding finding themes/popularity etc, no one was overly concern with ppl not finding them. See https://github.com/StylishThemes/GitHub-Dark/issues/683#issuecomment-403222564 and downwards.

I find this claim somewhat conflicting though, all themes in USO, have several GitHub links, so wouldnt anyone with ability to read, copy and paste or even click should find StyishThemes themes right here in the time the browser takes to load a new page?

**Comment by xt0rted** [comment]
If you use Stylish/Stylus you can find & install themes from USO for the site you're currently on. That's how I always looked for them because it was easier than going to their site. Doing that means I'd never see our messaging about no longer publishing to there.

**Comment by the-j0k3r** [comment]
Re: Stylus search topic https://github.com/openstyles/stylus/issues/375

I wonder how viable would it be to also use GitHub based searches on styles tags to something in Stylus. Like the tags here https://github.com/StylishThemes/StackOverflow-Dark like `usercss` etc.

**Comment by the-j0k3r** [comment]
> Great theme, stupid migration choice.

I think this is a little harsh, Blame Userstyles crew for publishing their addon as a basic tracking/spyware ability, no one sane would support their website or their methods, and they actually dont care about any of the users aside from what the users data can be used for in order to make them money.

**Comment by notmutiny** [comment]
While I agree it's somewhat harsh, that's how I feel about it. Stylus still has Userstyles embedded in the extension to support one-click style downloading. There is no debate that the overwhelming majority of Stylus users (the extension the authors are trying to promote) would not be able to find this theme due to the removal of the listing on userstyles.org.

This is how the extension is built to discover styles - no one will know this exists if they cannot see it.

Do not misunderstand: I support the authors moving to GitHub. However if you want to make a statement then the listing should still be on userscripts.org and the user should be notified that their installed version is outdated, development has stopped, and to go to this repo to reinstall the new version.

This will allow people to see that the style exists and have the ability to find the repo.

My issue is that the authors are essentially shooting themselves in the foot by removing themselves from 90% of their userbase and this will cause the amount of users to steeply decline. I've been using this style for what seems like years and not only was I convinced it wasn't available, but I was starting to question if it ever existed in the first place.

**Comment by the-j0k3r** [comment]
Perhaps the themes should not be archived in USO, and the @xt0rted notice added or something. The owners of the StylishThemes org have to make that decision though since we (maintainers)  dont have access to that portion.

Thanks for you patience in this, they are extremely busy ppl and we need to wait until they have a few minutes off their real life to comment here.

@Mottie and @silverwind for feedback pls.

**Comment by Mottie** [comment]
We archived all of our styles on USO because that was really the only option they provide.

Initially we did add a notice and stopped updating the style... that lead to numerous issues being opened about the white background header. Sadly, the last time I checked, our GitHub Dark style is so big that USO's server would time out and prevent us from updating. We couldn't add a notice nor update the style. If we completely removed the style, then users may potentially get an update of an empty style; that seemed more rude that archiving.

So the main issue was existing users not knowing how to update. All of our styles got a notice added to them. You can still go to our page to see it - https://userstyles.org/styles/37035/github-dark - and apparently still install the style without a button since I see 6 installs this week, but it won't show up while searching.

New users would have to depend on word-of-mouth to discover and install our styles. If https://openusercss.org/ ever gets updated (last update in 10/2018 😞) we'll move all of our styles there.

**Comment by silverwind** [comment]
If it is possible to have a live (e.g. not archived) style that does not have a install button but instead a link to GitHub, we could unarchive the styles and do that, but to my knowledge it's not possible to have a empty style on USO and any Install button is going to confuse users, so the current situation might be the best compromise.

**Comment by the-j0k3r** [comment]
Doesnt seem like this situation may change any time soon, Ill close this for now because everyone has chimed in, pin it, and if anything will be done by the owners, then they can reopen this or update or do something.

**Comment by spottedmahn** [comment]
>I only found this because I had the code installed on a separate machine and was able to find the archived webpage which led me to here

I was able to find it b/c I had opened issues in the repo before! 😂

I initially tried the stylish icon on my new PC but I couldn't find this theme.  Then I went to track it down on **https://userstyles.org/** so I could rate it and bump it up but I guess it's **not there**?

I wish GitHub issues had a TLDR concept so I didn't have to read tons of comments so I could find "the answer" 😂😊

**Comment by the-j0k3r** [comment]
> I wish GitHub issues had a TLDR concept so I didn't have to read tons of comments so I could find "the answer" joyblush

It sort of does, this issue is pinned and when you open an issue you have it at top like so.

![Capture](https://user-images.githubusercontent.com/31389848/72043130-ac9fad00-32b0-11ea-9979-649f48bff554.PNG)

>Then I went to track it down on https://userstyles.org/ so I could rate it and bump it up but I guess it's not there?

It is there, userstyles [doesn't show archived themes on searches](https://userstyles.org/styles/37035/github-dark) but then again it doesn't matter what they do anymore. We dont support Stylist extension nor the website in any case.

Things could always be better and we are always looking for help in improving them, so feel free to make some suggestions.
