### ISSUE TITLE
Compatiblity for Userscripts

### ISSUE THREAD

**Issue by SmartManoj** [StylishThemes/StackOverflow-Dark#164]
https://github.com/Benjol/SE-AutoReviewComments/issues/173
https://github.com/soscripted/sox/issues/406

**Comment by the-j0k3r** [comment]
Hello @SmartManoj! Thank you for reaching out to us with this request.

Can you please elaborate what you mean?

**Comment by SmartManoj** [comment]
Using black theme those repo's text are hidden

**Comment by the-j0k3r** [comment]
Please [see this comment](https://github.com/StylishThemes/GitHub-Dark/issues/960#issuecomment-505557739).

**Comment by the-j0k3r** [comment]
ping

**Comment by SmartManoj** [comment]
Not regarding system mode ;

**Comment by the-j0k3r** [comment]
Sorry, can you please elaborate, You provide minimal info, it doesnt help me or anyone to understand whats actually going on. So Ill ask again, can you please elaborate?

**Comment by SmartManoj** [comment]
> [Benjol/SE-AutoReviewComments#173](https://github.com/Benjol/SE-AutoReviewComments/issues/173)
> [soscripted/sox#406](https://github.com/soscripted/sox/issues/406)

When using those scripts and dark them , the buttons are not visible

**Comment by SmartManoj** [comment]
https://user-images.githubusercontent.com/7231077/60157457-6b601800-980c-11e9-944f-b4ba8c8a282e.png

**Comment by the-j0k3r** [comment]
@Mottie any ideas about this?

**Comment by Mottie** [comment]
It appears that those userscripts are adding the buttons - I didn't install them to test - so to me, this is outside the scope of our Stack Overflow dark theme. I say this because it is difficult to maintain external addons, extensions and/or userscripts when no one on the team uses them.

@SmartManoj I don't know your CSS skils, but adding a background & text color to those buttons should not be difficult. Right-click on one of those buttons and look for unique class or id. Use Stylus, or whatever user style manager, to write a new style that targets those buttons. If you need help, then after right-clicking on the button, find the wrapper of all the buttons and share the HTML here; we'll try to help, but I doubt we'd add it to this dark style.

**Comment by SmartManoj** [comment]
https://github.com/soscripted/sox/issues/406#issuecomment-513516995

**Comment by the-j0k3r** [comment]
Glad you found the classes and fix.

you can make a style with those selectors using the same @-moz-document fields as SO.

Since this is outside the purview of this style, Im closing this request.

Thanks for the updates.
