### ISSUE TITLE
Style applied to non-Stack Overflow search engine domain when query contains URL

### ISSUE THREAD

**Issue by chocmake** [StylishThemes/StackOverflow-Dark#168]
* **Browser**: Vivaldi
* **Operating System**: Windows 8.1
* **Link to page with the issue**: https://duckduckgo.com/?q=site%3Areverseengineering.stackexchange.com+bounty&ia=web
* **Screenshot**:
![Screenshot](https://user-images.githubusercontent.com/34178938/61112175-9ca83b80-a4ce-11e9-96ad-84bfd4bbd96d.png)

Appears the userstyle is applied to non Stack Overflow sites, here DuckDuckGo that happens to be searching with a query containing a related domain.

**Comment by the-j0k3r** [comment]
@chocmake Thank you for reaching out to us with this issue report. =)

Good find! The issue lies in this regex `^https?://((?!(www|area51)).*\.)?stackexchange\.com.*` located around line 90

https://github.com/StylishThemes/StackOverflow-Dark/blob/aa713158772b7db33ab6533cc884c290f60079e8/stackoverflow-dark.user.css#L90

Seems that simply excluding duckduckgo is sufficient here to handle this.

Bare with me for a while.
