### ISSUE TITLE
Should we redefine the existing vendor color classes?

### ISSUE THREAD

**Issue by AfroThundr3007730** [StylishThemes/StackOverflow-Dark#172]
So I noticed something while trying to hunt down the proper selector for another unstyled element:

![Screenshot_2019-07-20 User AfroThundr](https://user-images.githubusercontent.com/7613032/61573430-1d060800-aa9e-11e9-9801-e95ef270664e.png)

I noticed the background style is being applied using class `bg-green-050`, which is part of a library of classes for specific background colors defined in `stacks.css` (an un-minified version can be found [here](https://gist.github.com/AfroThundr3007730/4c1afd00d034b1c3d77c05cd6835f19f#file-stacks-css-L2691-L2693)).

Should we maybe redefine these with dark equivalents that match the theme? I wonder if it would be a better approach than having to override them with other types of selectors later.

**Comment by the-j0k3r** [comment]
@AfroThundr3007730 Hi there.

Yes, we should always use the right classes instead rather than to override them with other types of made up selectors, This is something Ive been trying to do in this style with borders/text colors and some of the backgrounds also.

Same with the `!important` usage, only use !important where it absolutely must be used.

The problem is that this style was mostly done not following those guidelines and now sometimes the result leads us to increase selector specificity and add other hacks in order to to get things to work.

Im trying to correct hat by also removing `:not` exclusions and general sweeping general selectors like span/div etc.

If you have a go at this try not to introduce any new color for green/red/etc shades and avoid plain black and pure white also.

**Comment by the-j0k3r** [comment]
Ive added two more commits with various fixes the last update Ill wait till making another release because I may d more today or maybe you add these fixes you noticed, (since I cant actually see that issue you reported for not having config options on my rep)

**Comment by xt0rted** [comment]
I haven't really followed this repo so I'm not sure if this has been mentioned before, but the colors (and all of their other design elements) can be [found here](https://stackoverflow.design/product/base/colors) and the repo with the less files is at [StackExchange/Stacks](https://github.com/StackExchange/Stacks).

**Comment by the-j0k3r** [comment]
@xt0rted thanks for that, really helpful if we want to do a re-write or have a look for reference.

**Comment by the-j0k3r** [comment]
@AfroThundr3007730 If you can, please submit a fix, I cant duplicate this for lack of being able to see this menu so fix would be blind (not enough points I only have the informed badge lol)

**Comment by xt0rted** [comment]
I can see this as well. There's two other issues I'm noticing here which are the tool tip is positioned under the other elements (doesn't happen when this style is disabled) and the `+50` labels seem really light.

![image](https://user-images.githubusercontent.com/831974/61645472-a96a2380-ac74-11e9-84db-776fa12503ba.png)

**Comment by the-j0k3r** [comment]
Yea no idea about z-indexes here eiher Ive noticed this around other places also.

**Comment by AfroThundr3007730** [comment]
When I have some time, I'll submit a patch for this. Been a bit busy lately.

**Comment by the-j0k3r** [comment]
> Not sure if we want to start tweaking the z-indexes.

I tried that on a similar related issue in this style, for some reason it had no effect and I lacked the interest to follow through. No idea why applying a style would break z-indexes anyway.

**Comment by AfroThundr3007730** [comment]
> I also see in @xt0rted screenshot two elemets +50 that need to be added to the correct rule with the darked green background.

What green class was that again? Also those match the other rep increase marker that appears in the title bar notifications, so I guess they'd all need to be changed. Can't test this til I get another rep bump though. :/

**Comment by xt0rted** [comment]
The top bar selector is `.top-bar .indicator-badge._positive` and on the activity page they use `.bg-green-400`.

**Comment by xt0rted** [comment]
I was playing around with this style some and found what's causing the tooltips to show under the other elements. It's due to this rule and specifically this selector `a:not([href*=".com"]):not([href*="?page="]):hover`.

https://github.com/StylishThemes/StackOverflow-Dark/blob/e45ef36fa69704bc96fa0d1a1d7ef367a6f4fba4/stackoverflow-dark.user.css#L1884-L1888

The `filter` property creates a new stacking context and that causes the item in question to show out of order from what you'd normally expect. @the-j0k3r mentioned this being an issue elsewhere and it's probably due to using `filer`, `opacity`, or another property which create a new stacking context.

**Comment by AfroThundr3007730** [comment]
Huh, never knew that. I assume we don't want to fix that by manually specifying z-indexes, but I don't really see an alternative (aside from not using a filter).

**Comment by the-j0k3r** [comment]
Thx, there is another way to do this but its not brighter on hover but darker, its fine and it wont break this I dont think.

**Comment by AfroThundr3007730** [comment]
Well, that seems to have fixed it:

![Screenshot_20190729_070945](https://user-images.githubusercontent.com/7613032/62055163-94f4d080-b20a-11e9-91f6-71d83ef1bf89.png)

At least in that particular case, haven't tested any other instances.

**Comment by the-j0k3r** [comment]
Theres another filter in use here https://github.com/StylishThemes/StackOverflow-Dark/blob/6d459106b054e4b66b61250683fdddf0fc4e5017/stackoverflow-dark.user.css#L272

try removing that, is it works Ill do this another way.

**Comment by xt0rted** [comment]
That one is coming from this rule.

https://github.com/StylishThemes/StackOverflow-Dark/blob/6d459106b054e4b66b61250683fdddf0fc4e5017/stackoverflow-dark.user.css#L299-L302

**Comment by the-j0k3r** [comment]
I guess its time to hack the hack

**Comment by AfroThundr3007730** [comment]
Looks like that got it:

![fixed](https://user-images.githubusercontent.com/7613032/62087881-dad58700-b252-11e9-9ad5-5c5800d4be67.png)
