### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/StackOverflow-Dark#180]
It looks like the folks at Stack Exchange are exploring the possibility of supporting dark mode.

https://github.com/StackExchange/Stacks/pull/356

If that ever does make it into production, I think this style will still exist. It'll just be a bit smaller. I'd still want to keep my custom color and background image 😉

**Comment by the-j0k3r** [comment]
This style needs a re-write in any case, its reached the point its becoming unmaintainable due to bad styling practices in the past like adding styles to glob and other things like div/span etc.

Ive tried addressing some of the issues but its completely bombed in some areas. Hence why Im pushing for the style generator we can simply plug into any site we want.

**Comment by FranklinYu** [comment]
https://stackoverflow.blog/2020/03/30/introducing-dark-mode-for-stack-overflow/ 🎉 

It’s only available on Stack Overflow (not even Stack Overflow Meta), but it’s a good signal! We’ll see how it goes.

**Comment by the-j0k3r** [comment]
Still prefer our color scheme

**Comment by AfroThundr3007730** [comment]
Yep, it's just nice to have a dark theme built into the site for when I'm at work or somehwere that I can't load userstyles. This version is still superior IMHO.

**Comment by Dorson** [comment]
No need for user logins to have the Dark Mode as an option.

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function without logins.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:
