### ISSUE TITLE
Dark elements in chat transcripts

### ISSUE THREAD

**Issue by athlonusm** [StylishThemes/StackOverflow-Dark#184]
Chat transcripts are using some of the current site's styles instead of this theme.

Here are some screenshots, taken on English Language & Usage. You could go there yourself, by the way—I can do that even logged out. Just make sure you go to the transcript of the chat rather than entering the chat as a participant.

![Eng_Dark](https://user-images.githubusercontent.com/32931827/65821269-af135500-e233-11e9-8dd7-4cc2094268f4.PNG)

Usernames:
![Eng_Usernames_CSS](https://user-images.githubusercontent.com/32931827/65821276-bb97ad80-e233-11e9-95f5-821216521810.PNG)

"2 hours later...":
![Eng_SysMsg_CSS](https://user-images.githubusercontent.com/32931827/65821279-bf2b3480-e233-11e9-8230-de58b6a1afeb.PNG)

The color is brown here because it seems to be in the site's CSS. On English Language Learners, for example, it's black.

**Comment by the-j0k3r** [comment]
@athlonusm Thanks for reporting this issue. Should be fixed in  v3.3.32 please update your style to reflect that version.

If you do find more issues , dont hesitate to report them, please keep in mind a specific links to a page or a specific chat room are always better in order to be able to exactly duplicate the issues.

Thanks and have a nice weekend.
