### ISSUE TITLE
Google reCaptcha affected on every page

### ISSUE THREAD

**Issue by tflori** [StylishThemes/StackOverflow-Dark#185]
* **Browser**: Firefox 69.0.2 with Stylus 
* **Operating System**: KDE neon 5.16 (Ubuntu 18.04)
* **Link to page with the issue**: https://portal.reiseversicherung.de/web/de_erv_customer/kundigung
* **Screenshot**: 
![grafik](https://user-images.githubusercontent.com/4855611/67189220-1dd86e00-f3ee-11e9-980a-72d8e29fd855.png)

IMO a userstyle should not affect different pages than it is implemented. In this case: then the recaptcha (f***ing iframe implementation) is still white on stackoverflow - so what?

It would be enough to remove this regex from the list: `/https?://(www\.)?google.com/recaptcha/api2/.*/`

**Comment by the-j0k3r** [comment]
I added this so it is by design of sorts except that it does apply to every page.

I can make the reCaptcha its own style (which is what Im inclined to do) but if I remove that regex even stackoverflows reCaptcha's wont be styled since they are/were inside an iframe So only way to style it was to do this.

Once I remove it, you will need that new style if you want any reCaptcha's darkening.

Bare with me.

**Comment by the-j0k3r** [comment]
Ok this should be now gone, when I have the reCaptcha style published Ill let you know just in case youre interested.

**Comment by the-j0k3r** [comment]
I forgot briefly to update here. Published a global standalone theme for Google reCAPTCHA at https://github.com/StylishThemes/Google-reCAPTCHA-Dark.
