### ISSUE TITLE
Ask Ubuntu

### ISSUE THREAD

**Issue by auscompgeek** [StylishThemes/StackOverflow-Dark#19]
[Ask Ubuntu](//askubuntu.com) is also an official Stack Exchange website. I noticed that it's not targeted by this style.

I tried adding `domain("askubuntu.com")` to the `@-moz-document` rule, but it misses a few things, notably the Ubuntu navbar in the header, and the Stack Exchange footer.

Is there any particular reason why Ask Ubuntu isn't being styled? Are there any plans to style it? (I presume you simply didn't encounter it whilst looking for Stack Exchange sites that needed styling.)

**Comment by Mottie** [comment]
Hey @auscompgeek!

Mostly because I was overwhelmed with trying to support all the different Stack Exchange sites and their minor differences. The Ask Ubuntu site has a navigation bar across the top that is not on any other Stack Exchange site.

Same idea with gaming.stackexchange.com... too much specific styling to add when I was just trying to cover "most" sites at the time.

I would surely welcome some help!

**Comment by Mottie** [comment]
askubuntu.com is now supported... it may not be purdy, but it works.
