### ISSUE TITLE
Support Enterprise urls

### ISSUE THREAD

**Issue by derekantrican** [StylishThemes/StackOverflow-Dark#204]
Should support [enterprise stackoverflow](https://stackoverflow.com/enterprise) urls. EG: `https://stackoverflow.[^\.]*.com/.*` (maybe my regex could be improved but the general form is `https://stackoverflow.DOMAIN.com/*`)

**Comment by the-j0k3r** [comment]
@derekantrican I'm not sure its just as easy as adding a regexp is it?

None of us has enterprise access, I don't anyway, so my concern is mainly for styling fixes since we cant inspect the classes, if so how are we suppose to fix any issues?

On the other hand, assuming there is no such problem, then its OK by me,

In any case **_we_ definitely would benefit from collaborators with enterprise access** to take on any arising issues and we welcome anyone interested in learning or help out in with this.

@Mottie @silverwind

**Comment by derekantrican** [comment]
I'd be willing to test and attempt to fix issues. I'm still a learner to CSS, but I've messed around with making a couple of my own userstyles always willing to learn more.

That being said, I changed the domains in the StackOverflow-Dark to include stackoverflow.microsoft.com and it seemed to work just fine (see below)

![](https://i.imgur.com/vjFlYQ1.png)

**Comment by the-j0k3r** [comment]
Feel free to submit a PR :+1:
