### ISSUE TITLE
Make bold text stand out as much as it does in the light theme

### ISSUE THREAD

**Issue by tophf** [StylishThemes/StackOverflow-Dark#211]
**Describe the change you'd like**

Observed in Windows 10 with cleartype enabled, pretty much the default setup.

Currently the bold text is almost indiscernible in a paragraph on a quick glance:

![image](https://user-images.githubusercontent.com/1310400/76726289-c6061f00-6761-11ea-8527-17b3550e771d.png)

However it really stands out in the original light theme:

![image](https://user-images.githubusercontent.com/1310400/76726347-e8983800-6761-11ea-9459-d4f2837f5c1b.png)

A possible solution is to set a brighter color e.g. `#fff`: 

![image](https://user-images.githubusercontent.com/1310400/76726445-3745d200-6762-11ea-93bb-b2a275d7d2c2.png)

**Comment by the-j0k3r** [comment]
This is how it looks here also Windows 10 with cleartype.

![Capture](https://user-images.githubusercontent.com/31389848/76728426-f3010480-6756-11ea-937e-cf8daa7e2f46.PNG)

Over here all `.post-text` is set to `#cccccc` that includes strong, the comment text is mistakenly set to `#dddddd` so that may explain it.
What I have done dim down comment text to `#ccc` and forcefully set strong to `#ddd`

![Capture](https://user-images.githubusercontent.com/31389848/76731245-3cece900-675d-11ea-8b19-e357c6a6389b.PNG)

Because all screens are not made equal so YMMV. 

In that case let me know.

Ideally I would like to make text colors customizable, but we are a long way away from an ideal situation rule wise to be able to go in that direction #175...

=)

P.S. on an unrelated matter, do you have an email I could reach you at?

**Comment by tophf** [comment]
It's better although I like my #fff more because even on your gifs the original theme's bold text is bolder.

> do you have an email 

AFAIK the one listed in my profile is working.

**Comment by the-j0k3r** [comment]
> It's better although I like my #fff more because even on your gifs the original theme's bold text is bolder.

It may seem that way, but its actually the same color as non bold, I cant find any default rules to the opposite, but cant say I looked hard enough.

Try with 4.3.9, if your screen still feels like it could be better, I can at least try make the strong text color customizable or have another go.

**Comment by tophf** [comment]
> actually the same color as non bold

Yes, of course but I'm talking about optical density, which is a different thing. Put in simple terms, the bold text in the light theme aggressively jumps out whereas in the dark theme it seems more or less monolith.

With 4.3.9 it's slightly better (I said that already) in questions but comments haven't changed because they use `<b>`.

**Comment by tophf** [comment]
FWIW I ended up using #eee.

**Comment by the-j0k3r** [comment]
Those colors are too bright here, but feel free to use whatever you like, 4.4.1 [you can choose strong color](https://github.com/StylishThemes/StackOverflow-Dark/commit/ef4de0c4816ccc26e6cb86fd8ab3e5c8b2bc1130), not all strongs are there, so it will work for this.

**Comment by the-j0k3r** [comment]
Thanks for feedback =)

**Comment by xt0rted** [comment]
We went through this with GitHub Dark more than once. I'm not sure if the current colors are correct at this point (they don't match what's talked about in https://github.com/StylishThemes/GitHub-Dark/issues/537), but we're using `#d2d2d2` for plain text and `#dcdcdc` for **bold text**. The comment background on GitHub is darker than on Stack Overflow so these might be too light for use there.
