### ISSUE TITLE
Code span in comment has light text color

### ISSUE THREAD

**Issue by FranklinYu** [StylishThemes/StackOverflow-Dark#226]
* **Browser**: Firefox stable
* **Operating System**: macOS Catalina
* **Link to page with the issue**: https://unix.stackexchange.com/questions/412295/how-are-environment-variables-defined-in-a-gnome-terminal-session#comment739184_412302
* **Screenshot**:

<img width="554" alt="screenshot" src="https://user-images.githubusercontent.com/3153452/101996050-dfea7900-3c83-11eb-9e1f-5825960a13eb.png">

Despite the note for v5, I assumed that the Stack Exchange original light theme should still apply to inline code spans, to be consistent with code blocks.

**Comment by the-j0k3r** [comment]
Cant duplicate

![Capture](https://user-images.githubusercontent.com/31389848/102013857-02979300-3d53-11eb-87da-247a3650541d.PNG)

Either make sure youre using the latest version avalable or disable SO native dark theme.

**Comment by FranklinYu** [comment]
Hi, my understand of that style is that, it’s required *if* I want to have dark background for code. This is understandable, because having syntax highlight is a whole lot of work, and customization is hard. However, I feel that it should at least be easy if I want to use the *original* color (the one from Stack Exchange) for code. Wasn’t that the reason why the styles were split into two?

**Comment by the-j0k3r** [comment]
There can be a set of default root css vars in style, but I prefer not to (since Im the one that fixed this, I decided that way) and because its easier to use the separate style that is 100% customizable after user installs it as opposed to no customization at all.

Fell free to submit a defaut set of variables like this https://github.com/StylishThemes/StackOverflow-Dark/issues/218#issuecomment-698996037 only wrapped in root.

I dont think theres an issue with SO changing the vars anyway and doesnt matter either way.
