### ISSUE TITLE
Font color is black

### ISSUE THREAD

**Issue by SmartManoj** [StylishThemes/StackOverflow-Dark#241]
Site changed

* **Browser**:  
* **Operating System**:
* **Link to page with the issue**: 
* **Screenshot**:

![image](https://user-images.githubusercontent.com/7231077/163315182-5a8e89b6-e2a6-4fac-b42f-5b3d47aba52d.png)

Dirty Fix:

```
* {
color: rgb(183, 183, 183) !important;
}
```

After fix:
![image](https://user-images.githubusercontent.com/7231077/163315491-a2510576-a7d0-4d97-9f69-66325b24ea4d.png)

**Comment by the-j0k3r** [comment]
See https://github.com/StylishThemes/StackOverflow-Dark#additional-styles

**Comment by SmartManoj** [comment]
> See [StylishThemes/StackOverflow-Dark#additional-styles](https://github.com/StylishThemes/StackOverflow-Dark#additional-styles)

That's already being used.
Here syntax is not the problem but the text

**Comment by the-j0k3r** [comment]
auto update breaks when you edit style locally, you must force update the style manually.

Also you didn't fill in the issue template so no one can see and fix the issue if its syntax or something else + only @AfroThundr3007730 may submit fixes to style since I dont maintain style anymore and also he may not have time and we dont accept dirty fixes.

The owners of stylishthemes haven't been active in this repo for over two years, so for my money I would look elsewhere.
I do have my own style for stack sites etc, but I haven't published and dont have time to verify quality.

Until proper information is submitted the issue is invalid in any case.
