### ISSUE TITLE
Top bar buttons hover background needs to be darker

### ISSUE THREAD

**Issue by Pakirava-Datsuma** [StylishThemes/StackOverflow-Dark#85]
- these items hovered background is very light:
![f9rakmc9q7usz14if1ewaa](https://user-images.githubusercontent.com/1230991/30711430-58a4f320-9f11-11e7-85ff-3644a9089544.png)
- I changed it to this color (use from answers active tab background):
![hlw-ao6ksni-r4elnrki6g](https://user-images.githubusercontent.com/1230991/30711436-5c5c6ed0-9f11-11e7-9791-d7d191776047.png)
- I found there two classes for top-bar-buttons and changed them:
`
.top-bar .my-profile:hover,
.top-bar .secondary-nav .-item .-link:hover 
{
    background-color: #333333;
}
`
- applied to element:
`<a href="/users/…" class="my-profile js-gps-track" data-gps-track="profile_summary.click()">
            <div class="gravatar-wrapper-24" >…</div>
            <div class="-rep js-header-rep" title="…">…</div>
                <div class="-badges">…</div>
</a>`

**Comment by Mottie** [comment]
Hi @Pakirava-Datsuma!

This was recently fixed ([ref](https://github.com/StylishThemes/StackOverflow-Dark/commit/3a03b19e634993f354cd5e9553ad6f0f15eaa41a#diff-0)) and updated on userstyles.org, please make sure to manually update the style from there.

Also, I'm guessing you're still using Stylish because it hasn't been updating properly. Check out [Stylus](https://github.com/openstyles/stylus), it's better!

**Comment by Pakirava-Datsuma** [comment]
Thank you!
